# Which compiler
CC = gcc
# Where to install
INSTDIR = /usr/local/bin
# Where are include files kept
INCLUDE = .
# Options for development
CFLAGS = -g -Wall -ansi

all: nbits bele

nbits: nbits.c
	$(CC) nbits.c -o nbits

bele: bele.c
	$(CC) bele.c -o bele