[workspace]
members = [
'guess',
'ownership',
'module',
'collection',
'error',
'generic',
'traits',
'lifetime',
'test_demo',
'grep',
'closure',
'iterator',
'cargo',
'cargo2'
]

[profile.release]
panic = 'abort'

